# Generated 2021-08-30 from:
# /workspace/speechbrain/recipes/SLURP/direct/hparams/train_with_wav2vec2.yaml
# yamllint disable
# ############################################################################
# Model: Direct SLU
# Encoder: Pre-trained ASR encoder -> LSTM
# Decoder: GRU + beamsearch
# Tokens: BPE with unigram
# losses: NLL
# Training: SLURP
# Authors:  Loren Lugosch, Mirco Ravanelli 2020
# ############################################################################

# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1986
__set_seed: !apply:torch.manual_seed [1986]
output_folder: kl_div_correction
save_folder: kl_div_correction/save
train_log: kl_div_correction/train_log.txt

# Data files
# The SLURP dataset will be automatically downloaded in the specified data_folder
data_folder: slurp/
                          # e.g, /localscratch/SLURP
data_folder_rirs: slurp/
train_splits: [train_synthetic, train_real]
csv_train: kl_div_correction/train-type=direct.csv
csv_valid: kl_div_correction/devel-type=direct.csv
csv_test: kl_div_correction/test-type=direct.csv

tokenizer_file: slu_tokenizer.ckpt
asr_tokenizer_file: asr_tokenizer.ckpt
model_file: model.ckpt
skip_prep: false


# URL for the wav2vec2 model, you can change to benchmark diffrenet models
wav2vec2_hub: facebook/wav2vec2-base-960h

# Training parameters
number_of_epochs: 50
batch_size: 6
lr: 0.0003
lr_wav2vec2: 0.00001
token_type: unigram # ["unigram", "bpe", "char"]
sorting: random
ckpt_interval_minutes: 15 # save checkpoint every N min
num_asr_tokens: 1000


#freeze all wav2vec2
freeze_wav2vec2: false

#set to true to freeze the CONV part of the wav2vec2 model
freeze_wav2vec2_conv: true

# Model parameters
sample_rate: 16000
emb_size: 128
dec_neurons: 512
output_neurons: 51 # index(eos/bos) = 0
ASR_encoder_dim: 768
encoder_dim: 256

# Decoding parameters
bos_index: 0
eos_index: 0
min_decode_ratio: 0.0
max_decode_ratio: 10.0
slu_beam_size: 80
eos_threshold: 1.5
temperature: 1.25

dataloader_opts:
  batch_size: 6
  shuffle: true

epoch_counter: &id018 !new:speechbrain.utils.epoch_loop.EpochCounter

  limit: 50

# Models

wav2vec2: &id001 !new:speechbrain.lobes.models.huggingface_wav2vec.HuggingFaceWav2Vec2
  source: facebook/wav2vec2-base-960h
  output_norm: true
  freeze: false
  save_path: kl_div_correction/save/wav2vec2_checkpoint

enc: &id002 !new:speechbrain.nnet.containers.Sequential
  input_shape: [null, null, 768]
  lstm: !new:speechbrain.nnet.RNN.LSTM
    input_size: 768
    bidirectional: true
    hidden_size: 256
    num_layers: 2
  linear: !new:speechbrain.nnet.linear.Linear
    input_size: 512
    n_neurons: 256

output_emb_slu: &id003 !new:speechbrain.nnet.embedding.Embedding
  num_embeddings: 51
  embedding_dim: 128

dec_slu: &id004 !new:speechbrain.nnet.RNN.AttentionalRNNDecoder
  enc_dim: 256
  input_size: 128
  rnn_type: gru
  attn_type: content
  hidden_size: 512
  attn_dim: 512
  num_layers: 3
  scaling: 1.0
  dropout: 0.0


seq_lin: &id011 !new:speechbrain.nnet.linear.Linear
  input_size: 512
  n_neurons: 51

seq_lin_slu: &id005 !new:speechbrain.nnet.linear.Linear
  input_size: 512
  n_neurons: 51

env_corrupt: &id006 !new:speechbrain.lobes.augment.EnvCorrupt


  openrir_folder: slurp/
  babble_prob: 0.0
  reverb_prob: 0.0
  noise_prob: 1.0
  noise_snr_low: 0
  noise_snr_high: 15

modules:
  wav2vec2: *id001
  enc: *id002
  output_emb_slu: *id003
  dec_slu: *id004
  seq_lin_slu: *id005
  env_corrupt: *id006
  
slu_enc: &id007 !new:speechbrain.nnet.containers.Sequential
  input_shape: [null, null, 128]
  lstm: !new:speechbrain.nnet.RNN.LSTM
    input_size: 128
    bidirectional: true
    hidden_size: 256
    num_layers: 2
  linear: !new:speechbrain.nnet.linear.Linear
    input_size: 512
    n_neurons: 256

input_emb: &id008 !new:speechbrain.nnet.embedding.Embedding
  num_embeddings: 1000
  embedding_dim: 128

output_emb: &id009 !new:speechbrain.nnet.embedding.Embedding
  num_embeddings: 51
  embedding_dim: 128

dec: &id010 !new:speechbrain.nnet.RNN.AttentionalRNNDecoder
  enc_dim: 256
  input_size: 128
  rnn_type: gru
  attn_type: keyvalue
  hidden_size: 512
  attn_dim: 512
  num_layers: 3
  scaling: 1.0
  dropout: 0.0


model: &id013 !new:torch.nn.ModuleList
- [*id007, *id008, *id009, *id010,*id011]


model_slu: &id015 !new:torch.nn.ModuleList
- [*id002, *id003, *id004, *id005]
tokenizer: &id012 !new:sentencepiece.SentencePieceProcessor
asr_tokenizer: &id014 !new:sentencepiece.SentencePieceProcessor


pretrainer: !new:speechbrain.utils.parameter_transfer.Pretrainer
  collect_in: kl_div_correction/save/SLURP_tokenizer
  loadables:
    model: *id013
    tokenizer: *id012
    asr_tokenizer: *id014
  paths:
    model: /workspace/CKPT+2021-09-08+19-10-27+00/model.ckpt
    tokenizer: https://www.dropbox.com/s/w72vtnf273yjwu4/SLURP_51_unigram.model?dl=1
    asr_tokenizer: https://www.dropbox.com/s/o7gnouwdoqchotj/1000_unigram.model?dl=1


beam_searcher: !new:speechbrain.decoders.S2SRNNBeamSearcher
  embedding: *id003
  decoder: *id004
  linear: *id005
  bos_index: 0
  eos_index: 0
  min_decode_ratio: 0.0
  max_decode_ratio: 10.0
  beam_size: 80
  eos_threshold: 1.5
  temperature: 1.25
  using_max_attn_shift: false
  max_attn_shift: 30
  coverage_penalty: 0.


beam_searcher_nlu: !new:speechbrain.decoders.S2SRNNBeamSearcher
  embedding: *id009
  decoder: *id010
  linear: *id011
  bos_index: 0
  eos_index: 0
  min_decode_ratio: 0.0
  max_decode_ratio: 10.0
  beam_size: 80
  eos_threshold: 1.5
  temperature: 1.25
  using_max_attn_shift: false
  max_attn_shift: 30
  coverage_penalty: 0.


opt_class: !name:torch.optim.Adam
  lr: 0.0003

wav2vec2_opt_class: !name:torch.optim.Adam
  lr: 0.00001

lr_annealing: &id016 !new:speechbrain.nnet.schedulers.NewBobScheduler
  initial_value: 0.0003
  improvement_threshold: 0.0025
  annealing_factor: 0.8
  patient: 0

lr_annealing_wav2vec2: &id017 !new:speechbrain.nnet.schedulers.NewBobScheduler
  initial_value: 0.00001
  improvement_threshold: 0.0025
  annealing_factor: 0.9

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
  checkpoints_dir: kl_div_correction/save
  recoverables:
    model_slu: *id015
    wav2vec2: *id001
    scheduler: *id016
    lr_annealing_wav2vec2: *id017
    counter: *id018
augmentation: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
  sample_rate: 16000
  speeds: [95, 100, 105]

log_softmax: !new:speechbrain.nnet.activations.Softmax
  apply_log: true

log_softmax2: !new:speechbrain.nnet.activations.Softmax
  apply_log: false

seq_cost: !name:speechbrain.nnet.losses.nll_loss
  label_smoothing: 0.1

train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
  save_file: kl_div_correction/train_log.txt

error_rate_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats

cer_computer: !name:speechbrain.utils.metric_stats.ErrorRateStats
  split_tokens: true


